In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
a = np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
b.shape

(2, 3)

In [7]:
a

array([1, 2, 3])

In [8]:
a.shape

(3,)

In [9]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
b.dtype

dtype('int32')

In [11]:
b.ndim

2

In [12]:
print(type(a))

<class 'numpy.ndarray'>


In [13]:
print(type(b))

<class 'numpy.ndarray'>


In [14]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
c = range(10000)

In [17]:
%timeit [i**3 for i in c]

2.85 ms ± 58.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [18]:
c_numpy =np.arange(10000)


In [19]:
%timeit c_numpy**3

15.2 µs ± 111 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [20]:
l1 = range(10000)
l2 = [i**2 for i in range(10000)]

In [21]:
%timeit list(map(lambda x,y: x*y, l1, l2))

1.19 ms ± 18.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [22]:
a1 = np.array(l1)
b1 = np.array(l2)

In [23]:
%timeit a1*b1

7.75 µs ± 54 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [24]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [26]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.full((3,3),344)

array([[344, 344, 344],
       [344, 344, 344],
       [344, 344, 344]])

In [30]:
np.full((3,3),34.4, dtype = np.int)

array([[34, 34, 34],
       [34, 34, 34],
       [34, 34, 34]])

In [31]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [32]:
v = np.array([1,2,3])
v

array([1, 2, 3])

In [33]:
 np.tile(v,(3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [34]:
 np.tile(v,(3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [35]:
np.random.random()

0.43578907844535086

In [36]:
100*np.random.random()

17.161090354499585

In [37]:
50*np.random.random() + 2

17.534085076410427

In [38]:
np.random.random([3,3])

array([[0.73420369, 0.09702298, 0.03277397],
       [0.56869317, 0.27725176, 0.11814353],
       [0.1058567 , 0.15485996, 0.21421595]])

# ADVANCED NUMPY OPERATIONS IN PYTHON

In [39]:
a = np.linspace(1,50,100)

In [40]:
a

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [41]:
a.itemsize

8

In [42]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [43]:
np.arange(18).shape

(18,)

In [44]:
b = np.arange(18).reshape(2,3,3)

In [45]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [46]:
b.shape

(2, 3, 3)

In [47]:
np.arange(18).reshape(2,3,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [48]:
an = np.array([2,4,6,8,10,12,14,16,18])

In [49]:
an

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [50]:
an[0]

2

In [51]:
an[2]

6

In [52]:
an[2,4,6]

IndexError: too many indices for array

In [54]:
an[[2,4,6]]

array([ 6, 10, 14])

In [55]:
an[2:]

array([ 6,  8, 10, 12, 14, 16, 18])

In [56]:
an[2:5]

array([ 6,  8, 10])

In [57]:
an[0::2]

array([ 2,  6, 10, 14, 18])

In [58]:
ant = np.array([[1,2,3],[4,5,6],[7,8,9]])
ant

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
ant[2,2]

9

In [60]:
an>2

array([False,  True,  True,  True,  True,  True,  True,  True,  True])

In [61]:
ant[(ant>2) & (ant<5)]

array([3, 4])

In [62]:
s = np.arange(10)

In [63]:
t =s

In [64]:
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
t

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
t[0]=11

In [67]:
t

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [68]:
s

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [69]:
y = s[:]

In [70]:
np.shares_memory(t,s)

True

In [71]:
np.shares_memory(y,s)

True

In [72]:
np.shares_memory(ant,s)

False

In [73]:
k = s.copy()

In [74]:
k[0] = 12

In [75]:
s

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [76]:
k

array([12,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [77]:
np.shares_memory(k,s)

False

In [78]:
m = np.array([[1,2,3],[4,5,6]])

In [79]:
m.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [80]:
n = np.array([[7,8,9],[10,11,12]])
n

array([[ 7,  8,  9],
       [10, 11, 12]])

In [81]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
m == n

array([[False, False, False],
       [False, False, False]])

In [83]:
np.vstack((m,n))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [84]:
np.hstack((m,n))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [85]:
o = np.arange(1,10)

In [86]:
np.sin(o)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [87]:
np.cos(o)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [88]:
np.exp(o)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [89]:
o

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
np.sum(o)

45

In [91]:
np.median(o)

5.0

In [92]:
o.std()

2.581988897471611

In [93]:
f = np.arange(1,10).reshape(3,3)

In [94]:
f

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
np.linalg.det(f)

-9.51619735392994e-16

In [96]:
np.linalg.inv(f)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [97]:
np.linalg.eig(f)

(array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [98]:
p = f.T

In [99]:
p

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [100]:
f

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
np.dot(f,p)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [102]:
g  = np.array([1,1,0], dtype = bool)
h  = np.array([1,0,1], dtype = bool)

In [103]:
np.logical_or(g,h)

array([ True,  True,  True])

In [104]:
np.logical_and(g,h)

array([ True, False, False])

In [105]:
g == g

array([ True,  True,  True])

In [106]:
np.all(g==g)

True

In [107]:
i = np.array([[1,2],[3,4]])

In [108]:
i

array([[1, 2],
       [3, 4]])

In [109]:
i.sum()

10

In [110]:
i.sum(axis=0)

array([4, 6])

In [111]:
i.sum(axis=1)

array([3, 7])

In [112]:
i.max()

4

In [113]:
i.min()

1

In [114]:
i.argmax()

3

In [115]:
i

array([[1, 2],
       [3, 4]])

In [116]:
i.shape

(2, 2)

In [117]:
j = np.arange(1,10)

In [118]:
j.shape

(9,)

In [119]:
j

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
j[:,np.newaxis].shape

(9, 1)

In [121]:
np.sort(j)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
j = j[:,np.newaxis]

In [123]:
j

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])