## LINEAR ALGEBRA



Matrix Multiplication

Vectors

**Ques) Why use Linear Algebra at the backend of the ML algorithms?**

**Answ)** There are several reasons as stated below:

 **1)** If you think about any visualization, as we live in 3d world we can  visualize it in the 2d graph. But, when we consider more than 4 dimensions, its difficult to visualize the same. In ML algorithms, data would be mostly n-Dimensional data. Here, Linear Algebra would help. Linear Algebra helps extend anything from 2D or 3D world to nD world. So, it's going to give an intuition and visual representation of the building block. Understanding Kernels in SVM and SGD(Stochastic Gradient Descent) would be almost impossible.

 **2)** Working with Algorithm. Related with first reason itself but a slight difference. Finding weights in the model and their coefficients. These coeffeicients can be obtained through Linear Algebra. In the equation of line, we might have unknowns. Can create new algorithms from scratch. 

In [1]:
import numpy as np

In [2]:
a =np.array([3,4,5])

In [3]:
b = np.array([1,3,6])

In [4]:
print(np.dot(a,b))

45


In [5]:
print(np.cross(a,b))

[  9 -13   5]


In [6]:
x = np.matrix([[1,2,3,4],[5,6,7,8],[2,3,4,5],[6,7,8,9]])

In [7]:
x

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [2, 3, 4, 5],
        [6, 7, 8, 9]])

In [8]:
x.shape

(4, 4)

In [9]:
c = np.matrix([[1,4,5],[2,3,4],[5,6,8]])


In [10]:
c

matrix([[1, 4, 5],
        [2, 3, 4],
        [5, 6, 8]])

In [11]:
d =np.matrix([[2],[3],[9]])

In [12]:
d

matrix([[2],
        [3],
        [9]])

In [13]:
c.shape

(3, 3)

In [14]:
d.shape

(3, 1)

In [15]:
print(c*d)

[[ 59]
 [ 49]
 [100]]


In [16]:
d.T


matrix([[2, 3, 9]])

In [17]:
c.T

matrix([[1, 2, 5],
        [4, 3, 6],
        [5, 4, 8]])

In [18]:
5*c

matrix([[ 5, 20, 25],
        [10, 15, 20],
        [25, 30, 40]])

In [19]:
from numpy import linalg as LA

In [20]:
e = np.matrix([[1,3,1],[2,2,1],[3,5,3]])


In [21]:
e

matrix([[1, 3, 1],
        [2, 2, 1],
        [3, 5, 3]])

In [22]:
e.shape

(3, 3)

In [23]:
LA.matrix_rank(e)

3

In [24]:
LA.matrix_rank(c)

3

In [25]:
f = np.matrix([[1,2,3],[3,2,1],[1,1,1]])


In [26]:
f

matrix([[1, 2, 3],
        [3, 2, 1],
        [1, 1, 1]])

In [27]:
LA.matrix_rank(f)

2